export const CONCERNS = [
  {
    name: "Overthinking",
    days: "14 days",
    note: "Quiet the mental loops.",
    tint: "#EFE6FB",
    learn: ["Why overthinking happens", "How to interrupt mental loops", "Building calm and clarity"],
  },
  {
    name: "Anxiety",
    days: "14 days",
    note: "Steady the body first.",
    tint: "#EAF3EC",
    learn: ["What anxiety does physically", "Grounding when it spikes", "Shrinking the what-ifs"],
  },
  {
    name: "Stress & Burnout",
    days: "14 days",
    note: "Come back down.",
    tint: "#FBE9EE",
    learn: ["Your stress response", "Recovery that actually works", "Setting boundaries without guilt"],
  },
  {
    name: "Sleep",
    days: "14 days",
    note: "Fall asleep softer.",
    tint: "#E7F1FA",
    learn: ["The science of sleep", "Winding the mind down", "Building a wind-down ritual"],
  },
  {
    name: "Procrastination",
    days: "18 days",
    note: "Start before you feel ready.",
    tint: "#ECE9FA",
    learn: ["Why you avoid the task", "The two-minute start", "Finishing without perfectionism"],
  },
  {
    name: "Self-Confidence",
    days: "14 days",
    note: "Collect small proofs.",
    tint: "#FBF1DF",
    learn: ["Where the inner critic comes from", "Evidence over opinion", "Speaking up for yourself"],
  },
  {
    name: "Phone Addiction",
    days: "14 days",
    note: "Get your attention back.",
    tint: "#E9F0FB",
    learn: ["What the scroll does to focus", "Friction that works", "Replacing the reach"],
  },
  {
    name: "Relationships",
    days: "18 days",
    note: "Understand your patterns.",
    tint: "#FBEAF3",
    learn: ["Your attachment style", "Repair after conflict", "Saying the difficult thing kindly"],
  },
  {
    name: "Focus",
    days: "14 days",
    note: "One thing at a time.",
    tint: "#EAF6F4",
    learn: ["How attention really works", "Designing a focus block", "Coming back after a break"],
  },
  {
    name: "Low Mood",
    days: "21 days",
    note: "Small light, daily.",
    tint: "#F3EDFA",
    learn: ["Mood and behaviour loops", "Activation in tiny steps", "Noticing what lifts you"],
  },
] as const;
