/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AppAuthRouteImport } from './routes/app.auth'
import { Route as AppCareRouteImport } from './routes/app.care'
import { Route as AppCheckinRouteImport } from './routes/app.checkin'
import { Route as AppExercisesRouteImport } from './routes/app.exercises'
import { Route as AppGamingRouteImport } from './routes/app.gaming'
import { Route as AppGardenRouteImport } from './routes/app.garden'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppJourneyRouteImport } from './routes/app.journey'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppPathsRouteImport } from './routes/app.paths'
import { Route as AppPersonalityRouteImport } from './routes/app.personality'
import { Route as AppPracticeRouteImport } from './routes/app.practice'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppSafetyRouteImport } from './routes/app.safety'
import { Route as AppViaRouteImport } from './routes/app.via'
import { Route as AppPathPathIdRouteImport } from './routes/app.path.$pathId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AppRoute,
} as any)
const AppCareRoute = AppCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppGamingRoute = AppGamingRouteImport.update({
  id: '/gaming',
  path: '/gaming',
  getParentRoute: () => AppRoute,
} as any)
const AppGardenRoute = AppGardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneyRoute = AppJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppPathsRoute = AppPathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalityRoute = AppPersonalityRouteImport.update({
  id: '/personality',
  path: '/personality',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSafetyRoute = AppSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AppRoute,
} as any)
const AppViaRoute = AppViaRouteImport.update({
  id: '/via',
  path: '/via',
  getParentRoute: () => AppRoute,
} as any)
const AppPathPathIdRoute = AppPathPathIdRouteImport.update({
  id: '/path/$pathId',
  path: '/path/$pathId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/app/account': typeof AppAccountRoute
  '/app/auth': typeof AppAuthRoute
  '/app/care': typeof AppCareRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/exercises': typeof AppExercisesRoute
  '/app/gaming': typeof AppGamingRoute
  '/app/garden': typeof AppGardenRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/journey': typeof AppJourneyRoute
  '/app/library': typeof AppLibraryRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/paths': typeof AppPathsRoute
  '/app/personality': typeof AppPersonalityRoute
  '/app/practice': typeof AppPracticeRoute
  '/app/profile': typeof AppProfileRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/via': typeof AppViaRoute
  '/app/path/$pathId': typeof AppPathPathIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/app/account': typeof AppAccountRoute
  '/app/auth': typeof AppAuthRoute
  '/app/care': typeof AppCareRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/exercises': typeof AppExercisesRoute
  '/app/gaming': typeof AppGamingRoute
  '/app/garden': typeof AppGardenRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/journey': typeof AppJourneyRoute
  '/app/library': typeof AppLibraryRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/paths': typeof AppPathsRoute
  '/app/personality': typeof AppPersonalityRoute
  '/app/practice': typeof AppPracticeRoute
  '/app/profile': typeof AppProfileRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/via': typeof AppViaRoute
  '/app/path/$pathId': typeof AppPathPathIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/app/account': typeof AppAccountRoute
  '/app/auth': typeof AppAuthRoute
  '/app/care': typeof AppCareRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/exercises': typeof AppExercisesRoute
  '/app/gaming': typeof AppGamingRoute
  '/app/garden': typeof AppGardenRoute
  '/app/home': typeof AppHomeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/journey': typeof AppJourneyRoute
  '/app/library': typeof AppLibraryRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/paths': typeof AppPathsRoute
  '/app/personality': typeof AppPersonalityRoute
  '/app/practice': typeof AppPracticeRoute
  '/app/profile': typeof AppProfileRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/via': typeof AppViaRoute
  '/app/path/$pathId': typeof AppPathPathIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/chat'
    | '/app/account'
    | '/app/auth'
    | '/app/care'
    | '/app/checkin'
    | '/app/exercises'
    | '/app/gaming'
    | '/app/garden'
    | '/app/home'
    | '/app/insights'
    | '/app/journey'
    | '/app/library'
    | '/app/onboarding'
    | '/app/paths'
    | '/app/personality'
    | '/app/practice'
    | '/app/profile'
    | '/app/safety'
    | '/app/via'
    | '/app/path/$pathId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/api/chat'
    | '/app/account'
    | '/app/auth'
    | '/app/care'
    | '/app/checkin'
    | '/app/exercises'
    | '/app/gaming'
    | '/app/garden'
    | '/app/home'
    | '/app/insights'
    | '/app/journey'
    | '/app/library'
    | '/app/onboarding'
    | '/app/paths'
    | '/app/personality'
    | '/app/practice'
    | '/app/profile'
    | '/app/safety'
    | '/app/via'
    | '/app/path/$pathId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/chat'
    | '/app/account'
    | '/app/auth'
    | '/app/care'
    | '/app/checkin'
    | '/app/exercises'
    | '/app/gaming'
    | '/app/garden'
    | '/app/home'
    | '/app/insights'
    | '/app/journey'
    | '/app/library'
    | '/app/onboarding'
    | '/app/paths'
    | '/app/personality'
    | '/app/practice'
    | '/app/profile'
    | '/app/safety'
    | '/app/via'
    | '/app/path/$pathId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auth': {
      id: '/app/auth'
      path: '/auth'
      fullPath: '/app/auth'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/care': {
      id: '/app/care'
      path: '/care'
      fullPath: '/app/care'
      preLoaderRoute: typeof AppCareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkin': {
      id: '/app/checkin'
      path: '/checkin'
      fullPath: '/app/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exercises': {
      id: '/app/exercises'
      path: '/exercises'
      fullPath: '/app/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gaming': {
      id: '/app/gaming'
      path: '/gaming'
      fullPath: '/app/gaming'
      preLoaderRoute: typeof AppGamingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/garden': {
      id: '/app/garden'
      path: '/garden'
      fullPath: '/app/garden'
      preLoaderRoute: typeof AppGardenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journey': {
      id: '/app/journey'
      path: '/journey'
      fullPath: '/app/journey'
      preLoaderRoute: typeof AppJourneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/paths': {
      id: '/app/paths'
      path: '/paths'
      fullPath: '/app/paths'
      preLoaderRoute: typeof AppPathsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/personality': {
      id: '/app/personality'
      path: '/personality'
      fullPath: '/app/personality'
      preLoaderRoute: typeof AppPersonalityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/practice': {
      id: '/app/practice'
      path: '/practice'
      fullPath: '/app/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/safety': {
      id: '/app/safety'
      path: '/safety'
      fullPath: '/app/safety'
      preLoaderRoute: typeof AppSafetyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/via': {
      id: '/app/via'
      path: '/via'
      fullPath: '/app/via'
      preLoaderRoute: typeof AppViaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/path/$pathId': {
      id: '/app/path/$pathId'
      path: '/path/$pathId'
      fullPath: '/app/path/$pathId'
      preLoaderRoute: typeof AppPathPathIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAuthRoute: typeof AppAuthRoute
  AppCareRoute: typeof AppCareRoute
  AppCheckinRoute: typeof AppCheckinRoute
  AppExercisesRoute: typeof AppExercisesRoute
  AppGamingRoute: typeof AppGamingRoute
  AppGardenRoute: typeof AppGardenRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppJourneyRoute: typeof AppJourneyRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPathsRoute: typeof AppPathsRoute
  AppPersonalityRoute: typeof AppPersonalityRoute
  AppPracticeRoute: typeof AppPracticeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSafetyRoute: typeof AppSafetyRoute
  AppViaRoute: typeof AppViaRoute
  AppPathPathIdRoute: typeof AppPathPathIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAuthRoute: AppAuthRoute,
  AppCareRoute: AppCareRoute,
  AppCheckinRoute: AppCheckinRoute,
  AppExercisesRoute: AppExercisesRoute,
  AppGamingRoute: AppGamingRoute,
  AppGardenRoute: AppGardenRoute,
  AppHomeRoute: AppHomeRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppJourneyRoute: AppJourneyRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPathsRoute: AppPathsRoute,
  AppPersonalityRoute: AppPersonalityRoute,
  AppPracticeRoute: AppPracticeRoute,
  AppProfileRoute: AppProfileRoute,
  AppSafetyRoute: AppSafetyRoute,
  AppViaRoute: AppViaRoute,
  AppPathPathIdRoute: AppPathPathIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
